site_name: Yspeed Doc
theme: 
  name: material
  logo: assets/office.svg
  direction: ltr
  icon:
    edit: material/pencil 
    view: material/eye
  
  
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
    - header.autohide
    
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
    
plugins:
  - offline
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: Foufou-exe/Yspeed
      branch: dev
  - search


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Foufou-exe
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thibaut-maurras/
  consent:
    title: Cookie consent
    description: 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better
    actions:
      - accept
      - reject

  alternate:
    - name: Deutsch
      link: /de/
      lang: de
    - name: French
      link: /fr/
      lang: fr
    - name: Italien
      link: /it/
      lang: it 
    - name: Spanish
      link: /es/
      lang: es

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/Foufou-exe"  target="_blank" rel="noopener">Foufou-exe</a>